export const equipmentFields = [
  ["equipmentInsuranceType","Tipo de seguro"],
  ["equipmentSegment","Segmento"],
  ["equipmentPerson","Pessoa"],
  ["equipmentDocument","CPF ou CNPJ do Proponente"],
  ["equipmentProponent","Nome ou razão social do proponente"],
  ["equipmentDescription","Descrição dos equipamentos"],
  ["equipmentBrandModel","Marca e modelo"],
  ["equipmentYear","Ano de fabricação"],
  ["equipmentSerial","Número de série (se disponível)"],
  ["equipmentValue","Valor total dos equipamentos"],
  ["equipmentCep","CEP do local de utilização"],
  ["equipmentUse","Atividade e forma de utilização"],
  ["equipmentFinancing","Tipo de financiamento"],
  ["equipmentQuantity","Quantidade de equipamentos iguais"],
  ["equipmentBrand","Marca"],
  ["equipmentModel","Modelo"],
  ["equipmentChassis","Chassi"],
  ["equipmentResaleDate","Data de saída da revenda"],
  ["equipmentHasInvoice","Possui nota fiscal?"],
  ["equipmentInvoiceNumber","Número da nota fiscal"],
  ["equipmentInvoiceIssuer","Empresa emissora"],
  ["equipmentBasicLimit","Cobertura básica — limite (R$)"],
  ["equipmentTheftLimit","Roubo e/ou furto qualificado — limite (R$)"],
  ["equipmentElectricalLimit","Danos elétricos — limite (R$)"],
  ["equipmentLiabilityLimit","RC - Equipamentos — limite (R$)"],
  ["equipmentRentalLimit","Perda ou pagamento de aluguel — limite (R$)"],
  ["equipmentPlated","Emplacado?"],
  ["equipmentPlate","Placa"],
  ["equipmentMounted","Instalado em veículo terrestre?"],
  ["equipmentLegalSituation","Bem litigioso, falido, concordatário, de massa falida ou leilão?"],
  ["equipmentTerritory","Abrangência da cobertura"],
  ["equipmentLocation","Local determinado"],
  ["equipmentThirdParty","Operado por terceiros?"],
] as const;
